#!/bin/bash
#PBS -N out_myw_proj
#PBS -l nodes=1:ppn=12
#PBS -l pmem=8gb
#PBS -l walltime=02:00:00
#PBS -A open
#PBS -j oe

# Loading modules
module purge

# Go to the directory
cd  /storage/work/h/htn5098/DataAnalysis/src/jobs

echo "Job started on `hostname` at `date`"

# Creating job files

# Run the job
one=$(qsub MYW_extract_nc.pbs)
echo $one
two=$(qsub -W depend=afterok:$one MYW_aggr_data.pbs)
echo $two

echo "Job ended at `date`"