#!/bin/bash
#PBS -N out_myw_pro
#PBS -l nodes=1:ppn=10
#PBS -l pmem=4gb
#PBS -l walltime=02:00:00
#PBS -A open
#PBS -j oe

# Loading modules
module purge
module load r/3.4
module load gcc
module use /gpfs/group/dml129/default/sw/modules
module load netcdf/4.7.1-gcc7.3.1

# Go to the directory
cd  /storage/work/h/htn5098/DataAnalysis/ 

echo "Job started on `hostname` at `date`"

# Run the job
Rscript ./src/Rcodes/MYW_aggr_to_county.R *pr_* grid_daily

echo "Job ended at `date`"