#!/bin/bash
#PBS -N out_RET_pro
#PBS -l nodes=1:ppn=10
#PBS -l pmem=4gb
#PBS -l walltime=02:00:00
#PBS -A open
#PBS -j oe

# Loading modules
module purge
module load python

# Go to the directory
cd /storage/home/htn5098/work/DataAnalysis/src/jobs/

echo "Job started on `hostname` at `date`"

# Run the job
#R --file=../Rcodes/test_loop.R
python batchsub_RET_process_raw.py

echo "Job ended at `date`"