#!/bin/bash
#PBS -N out_dl_drive
#PBS -l nodes=1:ppn=10
#PBS -l pmem=4gb
#PBS -l walltime=02:00:00
#PBS -A open
#PBS -j oe

# Loading modules
module purge
module load r/3.4

# Go to the directory
cd  /storage/home/htn5098/work/DataAnalysis #$PBS_O_WORKDIR 

echo "Job started on `hostname` at `date`"

# Run the job
Rscript ./src/Rcodes/RET_downloading_raw.R https://drive.google.com/open?id=1vm_roWupfjavjp7d9-Vaa7NR8IBUfZJk control meta

echo "Job ended at `date`"