#!/bin/bash 
cd  /storage/home/htn5098/scratch/DataAnalysis/data/raw/gridMET # changing directory to where the files are stored
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pr_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pdsi_2018.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2016.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2017.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2018.nc 
