#!/bin/bash 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1979.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1980.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1981.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1982.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1983.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1984.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1985.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1986.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1987.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1988.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1989.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1990.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1991.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1992.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1993.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1994.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1995.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1996.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1997.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1998.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_1999.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2000.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2001.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2002.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2003.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2004.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2005.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2006.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2007.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2008.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2009.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2010.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2011.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2012.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2013.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2014.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2015.nc 
wget -nc -c -nd http://www.northwestknowledge.net/metdata/data/pet_2016.nc 
